# task settings
num_train_frames: 5000000
env_name: sawyer_door
policy_switch_frequency: 300
frame_stack: 1
action_repeat: 1
# train settings
num_seed_frames: 10000
# eval
eval_every_frames: 10000
num_eval_episodes: 10
# snapshot
save_snapshot: false
# misc
seed: 1
device: cuda
save_video: true
save_train_video: false
use_tb: true
replay_buffer_num_workers: 4
simple_buffer: true
# agent
lr: 3e-4
feature_dim: 50


forward_agent:
  _target_: agents.SACAgent
  obs_shape: ??? # to be specified later
  action_shape: ??? # to be specified later
  device: ${device}
  lr: ${lr}
  critic_target_tau: 0.005
  reward_scale_factor: 10.0
  use_tb: ${use_tb}
  hidden_dim: 256
  feature_dim: ${feature_dim}
  from_vision: false
  discount: 0.99
  # replay buffer
  replay_buffer_size: 5000000
  nstep: 1
  batch_size: 256
  with_replacement: true

backward_agent:
  _target_: agents.SACAgent
  obs_shape: ??? # to be specified later
  action_shape: ??? # to be specified later
  device: ${device}
  lr: ${lr}
  critic_target_tau: 0.005
  reward_scale_factor: 10.0
  use_tb: ${use_tb}
  hidden_dim: 256
  feature_dim: ${feature_dim}
  from_vision: false
  discount: 0.99
  # replay buffer
  replay_buffer_size: 5000000
  nstep: 1
  batch_size: 256
  with_replacement: true

hydra:
  run:
    dir: ./exp_local/${env_name}/fbrl/${seed}/${now:%Y.%m.%d.%H.%M.%S}