# task settings
num_train_frames: 5000000
env_name: sawyer_peg
frame_stack: 1
action_repeat: 1
discount: 0.99
# train settings
num_seed_frames: 10000
# eval
eval_every_frames: 10000
num_eval_episodes: 10
# snapshot
save_snapshot: false
# replay buffer
replay_buffer_size: 5000000
replay_buffer_num_workers: 4
nstep: 1
batch_size: 256
simple_buffer: true
with_replacement: true
# misc
seed: 2
device: cuda
save_video: true
save_train_video: false
use_tb: true
# agent
lr: 3e-4
feature_dim: 50

agent:
  _target_: agents.SACAgent
  obs_shape: ??? # to be specified later
  action_shape: ??? # to be specified later
  device: ${device}
  lr: ${lr}
  critic_target_tau: 0.005
  reward_scale_factor: 10.0
  use_tb: ${use_tb}
  hidden_dim: 256
  feature_dim: ${feature_dim}
  from_vision: false
  
hydra:
  run:
    dir: ./exp_local/${env_name}/oracle/${seed}/${now:%Y.%m.%d.%H.%M.%S}